# Use a Node 16 base image
FROM node:16-alpine 

# make the 'backend' folder the current working directory
WORKDIR /var/www/html/backend/

# copy both 'package.json' and 'package-lock.json' (if available)
COPY backend/package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY backend/ .

CMD [ "npm", "run", "start" ]
