version: "3.4"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3838:80
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 3000:3000
